"""empty message

Revision ID: 32b5fdbf5ca9
Revises: None
Create Date: 2016-02-26 10:13:37.163355

"""

# revision identifiers, used by Alembic.
revision = '32b5fdbf5ca9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filler_id', sa.Integer(), nullable=True),
    sa.Column('some_number', sa.Integer(), nullable=True),
    sa.Column('some_text', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['filler_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionnaire')
    op.drop_table('user')
    ### end Alembic commands ###
